export const GET_ANIME_LIST_PROCESS = 'GET_ANIME_LIST_PROCESS';
export const GET_ANIME_LIST_RESULT = 'GET_ANIME_LIST_RESULT';

export const GET_ANIME_DETAILS_PROCESS = 'GET_ANIME_DETAILS_PROCESS';
export const GET_ANIME_DETAILS_RESULT = 'GET_ANIME_DETAILS_RESULT';

export const GET_ANIME_SEARCH_PROCESS = 'GET_ANIME_SEARCH_PROCESS';
export const GET_ANIME_SEARCH_RESULT = 'GET_ANIME_SEARCH_RESULT';
